config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'comics#index'

  resources :comics
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
# frozen_string_literal: true

class Author < ApplicationRecord
end

app/models/comic.rb
# frozen_string_literal: true

class Comic < ApplicationRecord
  belongs_to :author

  # in an actual application, one would move these into a presenter
  after_create_commit lambda {
                        broadcast_append_to 'comics', locals: {
                                                        comic_row: self
                                                      },
                                                      target: 'comics'
                      }

  after_destroy_commit lambda {
                         broadcast_remove_to 'comics', target: self
                       }

  validates :name, presence: true, uniqueness: { scope: :author_id }
  scope :with_author, lambda {
    includes(:author)
  }
  scope :with_search_term, lambda { |term|
    return self if term.blank?

    joins(:author)
      .where(Comic.sanitize_sql_for_conditions(['comics.name LIKE ?', "%#{term}%"]))
      .or(
        Author.where(
          Author.sanitize_sql_for_conditions(['authors.name LIKE ?', "%#{term}%"])
        )
      )
  }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/comics_controller.rb
# frozen_string_literal: true

# this controller represents the backend route of our turbo search
class ComicsController < ApplicationController
  def index
    @comics = Comic.with_author
                   .with_search_term(search_params[:search])
                   .order(name: :asc)
  end

  def create
    @comic = Comic.new(comic_params)
    return head :ok if @comic.save

    @error = @comic.errors.full_messages.to_sentence
    head :unprocessable_entity
  end

  def destroy
    comic = Comic.find(params[:id])
    return head :ok if comic.destroy

    @error = I18n.t('.record_not_destroyed')
    head :unprocessable_entity
  end

  private

  def search_params
    params.permit(:search)
  end

  def comic_params
    params
      .require(:comic)
      .permit(:id, :name, :author_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/comics/_comic.html.erb
<%= render partial: 'comics/comic_row', locals: { indicator_class: 'alert alert-info', comic_row: comic_row } %>

app/views/comics/_comic_row.html.erb
<tr id="<%= dom_id(comic_row) %>" class="<%= indicator_class %>">
  <td>
    <%= comic_row.name %>
  </td>
  <td>
    <%= comic_row.author.name %>
  </td>
  <td>
    <%= link_to(comic_path(comic_row),  data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                }) do %>
      <i class="fa-solid fa-trash text-danger"></i>
    <% end %>
  </td>
</tr>

app/views/comics/_error.turbo_stream.erb
<turbo-stream action="update" target="error">
  <template>
    <div class="error">
      <%= error %>
    </div>
  </template>
</turbo-stream>

app/views/comics/_form.html.erb
<%= form_for :comic, url: comics_path, method: :post, data: { 'turbo-frame': 'comics' } do |f| %>
  <fieldset>
    <legend><%= t('.new') %></legend>
    <div class="mb-3">
      <label class="form-label">
        <%= Comic.human_attribute_name(:name) %>
        <%= f.text_field :name, class: 'form-control' %>
      </label>
    </div>
    <div class="mb-3">
      <label class="form-label">
        <%= Author.human_attribute_name(:name) %>
        <%= collection_select(:comic, :author_id, Author.all, :id, :name, { prompt: true } , { class: 'form-select' }) %>
      </label>
    </div>
    <%= f.submit class: 'btn btn-primary' %>
  </fieldset>
<% end %>

app/views/comics/_search.html.erb
<%= form_with url: comics_path, method: :get, data: { 'turbo-frame': 'comics', 'search-target': 'searchForm' } do |form| %>
  <%= form.label :search, t('.search'), class: 'form-label' %>
  <div class="input-group">
    <%= form.search_field :search, data: { 'search-target': 'searchField', action: 'search#search' }, value: params[:search], autocomplete: 'off', class: 'form-control'  %>
    <div class="user-select-none btn btn-primary" role="button" data-action="click->search#reset">X</div>
  </div>
<% end %>
<div class="alert alert-info mt-3">
  The <span class="text-info">highlighted</span> entries are new entries and are neither taken into account by the search field nor sorted.
</div>

app/views/comics/_table.html.erb
<turbo-stream action="update" target="comics_table">
  <template>
    <table class="table table-striped caption-top">
      <caption>
        <h1><%= t('.caption') %></h1>
      </caption>
      <thead>
        <tr>
          <th class="w-50">
            <%= Comic.human_attribute_name(:name) %>
          </th>
          <th class="w-25">
            <%= Author.human_attribute_name(:name) %>
          </th>
          <th class="w-25">
            <%= t('.functions') %>
          </th>
        </tr>
      </thead>
      <tbody id="comics">
        <%= render partial: 'comic_row', collection: @comics, locals: { indicator_class: 'old' } %>
      </tbody>
    </table>
  </template>
</turbo-stream>

app/views/comics/create.turbo_stream.erb
<%= render partial: 'error', locals: { error: @error } %>

app/views/comics/destroy.turbo_stream.erb
<%= render partial: 'error', locals: { error: @error } %>

app/views/comics/index.html.erb
<div data-controller="search">
  <details>
    <summary><%= t('.new') %></summary>
    <%= render 'form' %>
  </details>
  <%# render the search form %>
  <div class="w-25">
    <%= render 'search' %>
  </div>
  <%# we will show an error if something went wrong %>
  <%= turbo_frame_tag "error" do %>
  <% end %>
  <%# this represents the table %>
  <%= turbo_stream_from "comics" %>
  <%= turbo_frame_tag 'comics_table' do %>
    <%= render partial: 'table', locals: { comics: @comics } %>
  <% end %>
</div>

app/views/comics/index.turbo_stream.erb
<%= render partial: 'table', locals: { comics: @comics } %>

app/views/comics/search.turbo_stream.erb
<%= render partial: 'table', locals: { comics: @comics } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FunWithTurbo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="m-3 w-75">
      <%= yield %>
    </div>
  </body>
</html>